title: Bjørn Helge Lervåg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1931545820552856
  brandStrength: 0.1845878
  lightness: 0.03284820774570107
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  rhythmicContrast: 0.4269560610409826
typography_spectrum: 0.8775650640018284
description: ''
layout_spectrum: 0.1905618889722973
name: Bjørn Helge Lervåg
